version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8081:8080"  # Cambié el puerto externo de 8080 a 8081
    volumes:
      - .:/app 
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge


